routes/web.php
<?php

use App\Http\Controllers\NotesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('notes/vue', [NotesController::class, 'vue'])->name('notes.vue');
Route::resource('notes', NotesController::class);

app/Models/Note.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Note extends Model
{
    use SoftDeletes;

    public $fillable = [
        'title',
        'body'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/API/NotesController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreNoteRequest;
use App\Http\Requests\UpdateNoteRequest;
use App\Models\Note;
use Illuminate\Http\JsonResponse;

class NotesController extends Controller
{
    /**
     * Display a listing of all notes.
     *
     * @return JsonResponse
     */
    public function index(): JsonResponse
    {
        return response()->json(Note::all());
    }

    /**
     * Store a newly created note in storage.
     *
     * @param StoreNoteRequest $request
     * @return JsonResponse
     */
    public function store(StoreNoteRequest $request): JsonResponse
    {
        return response()->json($this->noteService->store($request->all()));
    }

    /**
     * Display the specified note.
     *
     * @param Note $note
     * @return JsonResponse
     */
    public function show(Note $note): JsonResponse
    {
        return response()->json($note);
    }

    /**
     * Update the specified note in storage.
     *
     * @param UpdateNoteRequest $request
     * @param Note $note
     * @return JsonResponse
     */
    public function update(UpdateNoteRequest $request, Note $note): JsonResponse
    {
        return response()->json($this->noteService->update($note, $request->all()));
    }

    /**
     * Remove the specified note from storage.
     *
     * @param Note $note
     * @return JsonResponse
     */
    public function destroy(Note $note): JsonResponse
    {
        return response()->json($this->noteService->destroy($note));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use App\Services\NoteService;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    /**
     * @var NoteService
     */
    protected NoteService $noteService;

    /**
     * FaqController constructor.
     *
     * @param NoteService $noteService
     */
    public function __construct(NoteService $noteService)
    {
        $this->noteService = $noteService;
    }
}

app/Http/Controllers/NotesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreNoteRequest;
use App\Http\Requests\UpdateNoteRequest;
use App\Models\Note;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class NotesController extends Controller
{
    /**
     * Display a listing of all notes.
     *
     * @return View
     */
    public function index(): View
    {
        $notes = Note::all();

        return view('notes.index', compact('notes'));
    }

    /**
     * Show the form for creating a new note.
     *
     * @return View
     */
    public function create(): View
    {
        return view('notes.create');
    }

    /**
     * Store a newly created note in storage.
     *
     * @param StoreNoteRequest $request
     * @return RedirectResponse
     */
    public function store(StoreNoteRequest $request): RedirectResponse
    {
        $this->noteService->store($request->all());
        return redirect()->route('notes.index');
    }

    /**
     * Display the specified note.
     *
     * @param Note $note
     * @return View
     */
    public function show(Note $note): View
    {
        return view('notes.show', compact('note'));
    }

    /**
     * Show the form for editing the specified note.
     *
     * @param Note $note
     * @return View
     */
    public function edit(Note $note): View
    {
        return view('notes.update', compact('note'));
    }

    /**
     * Update the specified note in storage.
     *
     * @param UpdateNoteRequest $request
     * @param Note $note
     * @return RedirectResponse
     */
    public function update(UpdateNoteRequest $request, Note $note): RedirectResponse
    {
        $this->noteService->update($note, $request->all());

        return redirect()->route('notes.index');
    }

    /**
     * Remove the specified note from storage.
     *
     * @param Note $note
     * @return RedirectResponse
     */
    public function destroy(Note $note): RedirectResponse
    {
        $this->noteService->destroy($note);

        return redirect()->route('notes.index');
    }

    /**
     * Navigate to your vue root
     *
     * @return View
     */
    public function vue(): View
    {
        return view('notes.notes-spa');
    }
}

resources/views/layout/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"
          crossorigin="anonymous"
    >

    <title>@yield('title')</title>
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"
></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"
></script>

@hasSection('content')
    <div class="card">
        <div class="card-body">
            @yield('content')
        </div>
    </div>
@endif

@hasSection('vue')
    <div id="vue-root" class="card">
        <div class="card-body">
            @yield('vue')
        </div>
    </div>
    <script src="{{ mix('js/app.js') }}" type="text/javascript"></script>
@endif

</body>
</html>

resources/views/notes/create.blade.php
@extends('layout.base')
@section('title', 'New note')
@section('content')
    <form action="{{ route('notes.store') }}" method="post">
        {!! csrf_field()!!}
        <div class="form-group">
            <label class="control-label" for="title">Title</label>
            <input type="text"
                   required=""
                   name="title"
                   id="title"
                   class="form-control"
            >
        </div>

        <div class="form-group">
            <label class="control-label" for="body">Body</label>
            <textarea
                   name="body"
                   id="body"
                   class="form-control"
                   rows="10"
            ></textarea>
        </div>
        <button class="btn btn-success btn-block">Submit note</button>
    </form>
@endsection

resources/views/notes/index.blade.php
@extends('layout.base')
@section('title', 'Notes overview')
@section('content')
    <a href="{{ route('notes.create') }}" class="btn btn-primary mb-3">
        <strong>+</strong> New note
    </a>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Body</th>
                <th scope="col">Created at</th>
                <th scope="col">Updated at</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach($notes as $note)
                <tr>
                    <td>
                        <a href="{{ route('notes.show', $note) }}">
                            {{ $note->title }}
                        </a>
                    </td>
                    <td>{{ $note->body }}</td>
                    <td>{{ $note->created_at }}</td>
                    <td>{{ $note->updated_at }}</td>
                    <td>
                        <form action="{{ route('notes.destroy' , $note)}}" method="POST">
                            @method('delete')
                            {!! csrf_field()!!}
                            <button type="submit" class="btn btn-sm btn-danger">
                                <strong>x</strong> Verwijderen
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/notes/notes-spa.blade.php
@extends('layout.base')
@section('title', 'Vue notes')
@section('vue')
    <Notes />
@endsection

resources/views/notes/show.blade.php
@extends('layout.base')
@section('title', 'Note details')
@section('content')
    <a href="{{ route('notes.edit', $note) }}" class="btn btn-primary mb-3">
        Edit note
    </a>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">
                {{ $note->title }}
            </h5>
            <h6 class="card-subtitle mb-2 text-muted">
                Created: {{ $note->created_at }}
            </h6>

            <div class="card-text">
                {{ $note->body }}
            </div>
        </div>
    </div>
@endsection

resources/views/notes/update.blade.php
@extends('layout.base')
@section('title', 'Update note')
@section('content')
    <form action="{{ route('notes.update', $note) }}" method="post">
        @method('PUT')
        {!! csrf_field()!!}
        <div class="form-group">
            <label class="control-label" for="title">Title</label>
            <input type="text"
                   value="{{ $note->title }}"
                   required=""
                   name="title"
                   id="title"
                   class="form-control"
            >
        </div>

        <div class="form-group">
            <label class="control-label" for="body">Body</label>
            <textarea name="body" id="body" class="form-control" rows="10">{{ $note->body }}</textarea>
        </div>
        <button class="btn btn-success btn-block">Submit note</button>
    </form>
@endsection